name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Zestaw 4 testy
      id: zestaw-4-testy
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 50
        setup-command: pip install pytest schedule numpy pandas requests matplotlib
          multipledispatch
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ZESTAW-4-TESTY_RESULTS: "${{steps.zestaw-4-testy.outputs.result}}"
      with:
        runners: zestaw-4-testy
